/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.zero;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class AppTest {

    @Test
    public void should_parse_home_location() {
        Args args = Args.parse("rc.home", "/home/user/txtask_home_folder");

        assertThat(args.home(), is("/home/user/txtask_home_folder"));
    }

    @Test
    public void should_throw_exception_for_no_valued_home_switch() {
        CLIArgParserException exception = assertThrows(CLIArgParserException.class, () -> Args.parse("rc.home"));

        assertThat(exception.getMessage(), is("'rc.home' switch must have a value"));
    }

    @Test
    public void home_switch_must_be_required() {
        CLIArgParserException exception = assertThrows(CLIArgParserException.class, () -> Args.parse(""));

        assertThat(exception.getMessage(), is("'rc.home' is required!"));
    }

    @Test
    public void should_pass_remaining_parameters_to_filter() {
        Args args = Args.parse("rc.home", "/home/user/txtask_home_folder", "filter param 1", "filter param 2");

        assertThat(args.filter().get(0), is("filter param 1"));
        assertThat(args.filter().get(1), is("filter param 2"));
        assertThat(args.filter().size(), is(2));
    }
}
