/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.zero;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class AppTest {
    @Test
    public void should_parse_home_location() {
        Args args = Args.parse("rc.home", "/home/user/txtask_home_folder");

        assertThat(args.home(), is("/home/user/txtask_home_folder"));
    }
}
