/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.zero;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public Args parseCommandLine(String... cliArgs) {
        Args args = new Args();

        for (int i = 0; i < cliArgs.length; ) {
            String arg = cliArgs[i];


            if ("rc.home".equals(arg)) {
                String value = cliArgs[i + 1];

                args.home(value);

                i += 2;
            } else {
                i++;
            }
        }

        return args;
    }
}
